kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devnet-multiplier
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["devnet-origin-passwd"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devnet-multiplier
  labels:
    testnet: devnet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: devnet-multiplier-binding
  namespace: default
  labels:
    testnet: devnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devnet-multiplier
subjects:
- kind: ServiceAccount
  name: devnet-multiplier
  namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devnet-multiplier
  labels:
    testnet: devnet
spec:
  serviceName: devnet # has to match with the headless service's name
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      testnet: devnet
      app: multiplier
      type: multiplier
  template:
    metadata:
      labels:
        testnet: devnet
        app: multiplier
        type: multiplier
    spec:
      serviceAccountName: devnet-multiplier
      tolerations:
      - key: dedicated
        operator: Equal
        value: multiplier
        effect: NoSchedule
      # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service
      # dnsPolicy: None
      dnsConfig:
        nameservers:
        - 1.1.1.1
        - 8.8.8.8
        options:
        - name: timeout
          value: "2"
        - name: rotate
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1 # not need a very high value since tolerations is used
            preference:
              matchExpressions:
              - key: k8s.z7a.xyz/group
                operator: In
                values:
                - multiplier
      volumes:
      - name: zilliqa-config
        configMap:
          name: devnet-config
      - name: zilliqa-run
        emptyDir: {}
      - name: zilliqa-keys
        secret:
          secretName: devnet-config
      - name: local-config
        emptyDir: {}
      initContainers:
      - name: cleanup-keys
        image: zilliqa
        env:
        - name: Z7A_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: Z7A_TESTNET_NAME
          value: devnet
        command:
        - /bin/bash
        - -c
        - |
          set -e
          cp -rL /etc/zilliqa-config/* /etc/zilliqa/
          cp -rL /etc/zilliqa-secrets/* /etc/zilliqa/
          python /etc/zilliqa/init.py --pod-name $Z7A_POD_NAME --testnet devnet -n 20 -d 5 -l 1 --port 30303 --websocket=  --seed-multiplier --multiplier-fanout=2  --seed-node --transaction-sender=0 --ds-guard=4 --shard-guard=10    --bucket=76177407-1e06-4e24-85be-7f3071e3e79   --cleanup-private-keys
        volumeMounts:
        - mountPath: /etc/zilliqa
          name: local-config
        - mountPath: /etc/zilliqa-secrets
          name: zilliqa-keys
        - mountPath: /etc/zilliqa-config
          name: zilliqa-config
      containers:
      - name: zilliqa
        image: zilliqa
        # image: zilliqa/goduplicator:20190129
        imagePullPolicy: Always
        securityContext:
          privileged: true
        workingDir: /run/zilliqa
        env:
          - name: Z7A_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CLUSTER_NAME
            value: arn:aws:eks:us-west-2:210478221899:cluster/devnet
          - name: Z7A_TESTNET_NAME
            value: devnet
        volumeMounts:
        - mountPath: /run/zilliqa
          name: zilliqa-run
        - mountPath: /etc/zilliqa
          name: local-config
        ports:
        - containerPort: 30303
          name: zilliqa-app
        command:
        - /bin/bash
        - -c
        - |
          set -e
          sysctl -w net.core.somaxconn=32768
          touch readiness
          python /etc/zilliqa/init.py --pod-name $Z7A_POD_NAME --testnet devnet -n 20 -d 5 -l 1 --port 30303 --websocket=  --seed-multiplier --multiplier-fanout=2  --seed-node --transaction-sender=0 --ds-guard=4 --shard-guard=10    --bucket=76177407-1e06-4e24-85be-7f3071e3e79  
          # launch sequence
          chmod u+x ./start.sh
          echo "Running start.sh"
          ./start.sh
      imagePullSecrets:
      - name: ecr-creds
