apiVersion: v1
kind: Service
metadata:
  name: zilliqa-exporter
  namespace: default
  labels:
    app: zilliqa-exporter
    testnet: devnet
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: metrics
    port: 8081
    targetPort: 8085
  selector:
    app: zilliqa
    testnet: devnet
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zilliqa
  namespace: default
  labels:
    app: zilliqa
    testnet: devnet
spec:
  endpoints:
  - port: metrics
    scrapeTimeout: 15s
    relabelings:
    - action: replace
      targetLabel: cluster
      replacement: kind
    - action: replace
      targetLabel: testnet
      replacement: devnet
  selector:
    matchLabels:
      app: zilliqa-exporter
