name: Security scan

on:
  pull_request:
    branches:
    - master

jobs:
  sast-scan:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      name: Cache vdb
      with:
        path: |
          ${{ github.workspace }}/vdb
        key: ${{ runner.os }}/slscan
    - name: Scan
      uses: ShiftLeftSecurity/scan-action@v1.3.0
      env:
        VDB_HOME: ${{ github.workspace }}/vdb
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        type: "credscan,nodejs,depscan"
        output: reports
    - name: Upload scan reports
      uses: actions/upload-artifact@v3
      with:
        name: shiftleft-scan-reports
        path: reports

  trivy-scan:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout scm
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'
        vuln-type: library
        exit-code: 0